name: Build Python App

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:

  version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Code herunterladen
        uses: actions/checkout@v4

      - name: Version auslesen
        id: version
        run: |
          VERSION=$(cat version.txt)

          echo "version=$VERSION" >> $GITHUB_OUTPUT



  build-windows:
    needs: version
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: PyInstaller installieren
        run: pip install pyinstaller

      - name: Windows bauen
        run: pyinstaller --onefile --icon=icons/icon.ico --name JarLauncher-Windows --distpath launcher code/JarLauncher.py

      - uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: launcher/JarLauncher-Windows.exe



  build-linux:
    needs: version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: PyInstaller installieren
        run: pip install pyinstaller

      - name: AppImage Tools installieren
        run: |
          sudo apt update
          sudo apt install -y libfuse2

      - name: Linux Programm bauen
        run: |
          pyinstaller --onefile \
          --name JarLauncher \
          code/JarLauncher.py

      - name: AppImage vorbereiten
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          mkdir -p AppDir/usr/share/applications

          cp dist/JarLauncher AppDir/usr/bin/JarLauncher

          # AppImage Icon
          cp icons/icon.png AppDir/JarLauncher.png

          # Linux Icon Theme
          cp icons/icon.png AppDir/usr/share/icons/hicolor/256x256/apps/JarLauncher.png

          cat > AppDir/JarLauncher.desktop <<EOF
          [Desktop Entry]
          Name=JarLauncher
          Comment=Java Launcher Tool
          Exec=JarLauncher
          Icon=JarLauncher
          Type=Application
          Categories=Utility;
          EOF

          cp AppDir/JarLauncher.desktop AppDir/usr/share/applications/

      - name: AppImage erstellen
        run: |
          wget -q https://github.com/AppImage/appimagetool/releases/latest/download/appimagetool-x86_64.AppImage

          chmod +x appimagetool-x86_64.AppImage

          ARCH=x86_64 ./appimagetool-x86_64.AppImage \
          AppDir \
          JarLauncher-Linux.AppImage

      - uses: actions/upload-artifact@v4
        with:
          name: Linux-App
          path: JarLauncher-Linux.AppImage



  build-macos:
    needs: version
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: PyInstaller installieren
        run: pip install pyinstaller

      - name: macOS bauen
        run: |
          pyinstaller --windowed \
          --icon=icons/icon.icns \
          --name JarLauncher \
          --distpath launcher \
          code/JarLauncher.py

      - name: macOS App packen
        run: |
          cd launcher
          zip -r JarLauncher-macOS.zip JarLauncher.app

      - uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: launcher/JarLauncher-macOS.zip



  release:

    needs:
      - version
      - build-windows
      - build-linux
      - build-macos

    runs-on: ubuntu-latest

    steps:

      - name: Dateien herunterladen
        uses: actions/download-artifact@v4


      - name: GitHub Release erstellen
        uses: softprops/action-gh-release@v2

        with:
          tag_name: v${{ needs.version.outputs.version }}
          name: JarLauncher v${{ needs.version.outputs.version }}
          generate_release_notes: true

          files: |
            Windows-App/JarLauncher-Windows.exe
            Linux-App/JarLauncher-Linux.AppImage
            macOS-App/JarLauncher-macOS.zip
